# Generated by Django 5.2 on 2025-04-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userprofile_fecha_reset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hechizo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_gemas', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.CharField(choices=[('amor', 'Amor'), ('dinero', 'Dinero'), ('miselaneo', 'Misceláneo')], default='miselaneo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_gemas', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.CharField(choices=[('amor', 'Amor'), ('dinero', 'Dinero'), ('miselaneo', 'Misceláneo')], default='miselaneo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
