# Generated by Django 5.2 on 2025-04-11 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hechizo_pocion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraHechizo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('hechizo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hechizo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_hechizos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hechizo')},
            },
        ),
        migrations.CreateModel(
            name='CompraPocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('pocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pocion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_pociones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pocion')},
            },
        ),
    ]
