# Generated by Django 4.2.6 on 2025-04-12 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comprahechizo_comprapocion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaTarot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('imagen_nombre', models.CharField(max_length=100)),
                ('significado_normal', models.TextField()),
                ('significado_invertido', models.TextField()),
            ],
            options={
                'verbose_name': 'Carta de Tarot',
                'verbose_name_plural': 'Cartas de Tarot',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TipoTirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('basica', 'Tirada Básica'), ('claridad', 'Tirada de Claridad'), ('profunda', 'Tirada Profunda')], max_length=10)),
                ('num_cartas', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('costo_gemas', models.PositiveIntegerField(default=1)),
                ('limite_mensual', models.PositiveIntegerField(default=0)),
                ('layout_descripcion', models.TextField(help_text='Descripción de la disposición de las cartas')),
            ],
        ),
        migrations.CreateModel(
            name='TiradaRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pregunta', models.TextField()),
                ('interpretacion', models.TextField()),
                ('tipo_tirada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipotirada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartaEnTirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField(help_text='Número de posición en la tirada (1, 2, 3...)')),
                ('invertida', models.BooleanField(default=False)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cartatarot')),
                ('tirada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='api.tiradarealizada')),
            ],
            options={
                'ordering': ['posicion'],
            },
        ),
    ]
